// Augur — `place` (memory leaf): write the cohort's full roster as a load-on-demand
// memory file. Generalized from build-roster-memory.mjs. The roster lives as a LEAF so
// the whole membership is *in* the graph but never auto-read on a single-node lookup:
// MEMORY.md → MEMORY.community.md → MEMORY.roster.md (this grandchild).
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { expandHome } from "./cohort.mjs";

const esc = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");

export function placeMemory(cohort, roster) {
  const people = roster.people || [];
  const rank = (p) => (p.memoryNode ? 0 : p.github ? 1 : 2);
  const sorted = [...people].sort((a, b) => rank(a) - rank(b) || a.name.localeCompare(b.name));

  const row = (p) => {
    const gh = p.github ? `[${p.github}](https://github.com/${p.github})` : "";
    const loc = p.location || [p.city, p.country].filter(Boolean).join(", ") || "";
    const src = (p.source || []).map((s) => (s.startsWith("meetup") ? "M" : s.startsWith("luma") ? "L" : s)).join("+");
    const badges = [
      p.kind === "bridge" ? "🌉 bridge" : "",
      p.memoryNode ? `📌 [node](${p.memoryNode})` : "",
      p.crossRef ? "↔ big-graph" : "",
    ].filter(Boolean).join(" ");
    return `| ${esc(p.name)} | ${gh} | ${esc(loc)} | ${esc(p.role || "")} | ${src} | ${badges} |`;
  };

  const withGh = people.filter((p) => p.github).length;
  const promoted = people.filter((p) => p.memoryNode).length;
  const T = cohort.memory.title;

  const body = `# ${T} — FULL ROSTER (load-on-demand leaf)

<!-- GENERATED by \`augur place --cohort ${cohort.id}\` from the cohort's fused roster. Do not hand-edit — edit cohorts/${cohort.id}/data/overrides.json and re-run. -->

*Grandchild of [MEMORY.md](MEMORY.md) via [MEMORY.community.md](MEMORY.community.md). This holds ALL ${people.length} roster rows so the community graph is complete, but it is a LEAF that is read only when you deliberately open the full roster — it is never pulled into auto-loaded context. To find or promote one person, use [MEMORY.community.md](MEMORY.community.md) (the curated ${promoted} nodes); come here only for the full membership.*

**Roster:** ${people.length} people · ${withGh} with GitHub · ${promoted} promoted to their own memory node. Source of truth: the cohort's fused roster (\`augur fuse --cohort ${cohort.id}\`); the dashboard is \`augur render\`. Legend: **M**=Meetup, **L**=Luma · 🌉 bridge · 📌 own node · ↔ cross-ref to big graph.

| Name | GitHub | Location | Role | Src | |
|---|---|---|---|---|---|
${sorted.map(row).join("\n")}
`;

  const path = join(expandHome(cohort.memory.dir), cohort.memory.rosterFile);
  writeFileSync(path, body);
  return { count: people.length, withGh, promoted, path };
}
