// Augur — `render`: turn a fused cohort roster into the dashboard artifacts.
//   peopleJs(cohort, roster)          → the `window.<GLOBAL> = {…}` data script
//   dashboardHtml(cohort, {isPublic}) → the index.html (branding from cohort config)
//
// This is a NEW augur capability (#1670): augur had zero visualization. The CSS + client
// JS are lifted verbatim from the community dashboard (functional identity); only the
// branding strings, the data-global name, and the local-vs-public variations are
// parameterized. isPublic flips the node badge to the boolean field and swaps the footer.
import { expandHome } from "./cohort.mjs";

export function peopleJs(cohort, roster, { isPublic = false } = {}) {
  const banner = isPublic
    ? "// GENERATED public build (PII-stripped) by `augur publish`. Do not edit.\n"
    : "// GENERATED by `augur fuse` from cohorts/<id>/data/{meetup,luma,overrides,dig}.json.\n// Do not edit by hand — edit the sources and re-run. Loaded via <script>.\n";
  return `${banner}window.${cohort.globalVar} = ${JSON.stringify(roster, null, 2)};\n`;
}

export function dashboardHtml(cohort, { isPublic = false } = {}) {
  const b = cohort.brand;
  const badgeField = isPublic ? "p.node" : "p.memoryNode";
  const footer = isPublic
    ? `\n  ${b.publicSub}<br/>\n  Sibling dashboard (Robin): <a href="${b.footerSibling.url}">${b.footerSibling.label}</a>\n  · Last updated <span id="updated"></span>`
    : `\n  Canonical data: <code>build/people.js</code> · Memory graph:\n  <code>${expandHome(cohort.memory.dir)}/</code><br/>\n  Sibling dashboard (Robin): <a href="${b.footerSibling.url}">${b.footerSibling.label}</a>\n  · Last updated <span id="updated"></span>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${b.docTitle}</title>
<style>
  :root{
    --bg:#0b0e17; --panel:#141a28; --panel-2:#1b2233; --line:#26304a;
    --ink:#e8ecf6; --dim:#8b96b0; --accent:#8a7bff; --accent-2:#4ad6c5;
    --bridge:#f5b955; --chip:#212a40;
  }
  *{box-sizing:border-box}
  body{margin:0;background:radial-gradient(1200px 600px at 70% -10%,#171f36 0,var(--bg) 60%);
       color:var(--ink);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
  a{color:var(--accent-2);text-decoration:none} a:hover{text-decoration:underline}
  header{padding:34px 28px 10px;max-width:1080px;margin:0 auto}
  .kicker{letter-spacing:.22em;text-transform:uppercase;color:var(--accent);font-size:11px;font-weight:700}
  h1{margin:.15em 0 .1em;font-size:30px;font-weight:800}
  .sub{color:var(--dim);max-width:70ch}
  .wrap{max-width:1080px;margin:0 auto;padding:0 28px 60px}
  .bar{display:flex;gap:12px;flex-wrap:wrap;align-items:center;margin:22px 0 8px}
  input[type=search]{flex:1;min-width:220px;background:var(--panel);border:1px solid var(--line);
       color:var(--ink);padding:10px 14px;border-radius:10px;font-size:14px}
  .stat{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:8px 12px;color:var(--dim);font-size:13px}
  .stat b{color:var(--ink)}
  .filters{display:flex;gap:8px;flex-wrap:wrap;margin:4px 0 18px}
  .tag{background:var(--chip);border:1px solid var(--line);color:var(--dim);
       padding:4px 10px;border-radius:999px;font-size:12px;cursor:pointer;user-select:none}
  .tag.on{background:var(--accent);border-color:var(--accent);color:#0b0e17;font-weight:700}

  /* Bridge banner */
  .bridge{border:1px dashed var(--bridge);background:linear-gradient(90deg,rgba(245,185,85,.06),transparent);
          border-radius:14px;padding:14px 16px;margin:6px 0 26px;display:flex;gap:14px;align-items:center;flex-wrap:wrap}
  .bridge .b-ico{font-size:22px}
  .bridge .b-txt{color:var(--dim);font-size:13px;flex:1;min-width:240px}
  .bridge .b-txt b{color:var(--bridge)}

  section h2{font-size:13px;text-transform:uppercase;letter-spacing:.14em;color:var(--dim);
             border-bottom:1px solid var(--line);padding-bottom:8px;margin:26px 0 14px}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:14px}
  .card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px;
        display:flex;flex-direction:column;gap:10px;transition:.15s;position:relative;overflow:hidden}
  .card:hover{border-color:var(--accent);transform:translateY(-2px)}
  .card.bridge-card{border-color:var(--bridge)}
  .top{display:flex;gap:12px;align-items:center}
  .av{width:46px;height:46px;border-radius:50%;background:var(--panel-2);border:1px solid var(--line);
      display:grid;place-items:center;font-weight:800;color:var(--accent);font-size:17px;flex:none;overflow:hidden}
  .av img{width:100%;height:100%;object-fit:cover}
  .nm{font-weight:700} .rl{color:var(--dim);font-size:13px}
  .loc{color:var(--dim);font-size:12px}
  .note{color:#c3cbe0;font-size:13px}
  .chips{display:flex;gap:6px;flex-wrap:wrap}
  .chips .c{background:var(--chip);color:var(--dim);border-radius:999px;padding:2px 9px;font-size:11px}
  .links{display:flex;gap:12px;flex-wrap:wrap;font-size:13px;margin-top:2px}
  .badge{position:absolute;top:12px;right:12px;font-size:10px;letter-spacing:.1em;text-transform:uppercase;
         color:var(--dim);border:1px solid var(--line);border-radius:999px;padding:2px 8px}
  .badge.node{color:var(--accent-2);border-color:var(--accent-2)}
  footer{max-width:1080px;margin:0 auto;padding:20px 28px 50px;color:var(--dim);font-size:12px}
  .empty{color:var(--dim);padding:30px;text-align:center}
</style>
</head>
<body>
<header>
  <div class="kicker">${b.kicker}</div>
  <h1>${b.h1}</h1>
  <p class="sub">${b.sub}</p>
</header>

<div class="wrap">
  <div class="bar">
    <input id="q" type="search" placeholder="Search name, role, location, handle, tag…" autocomplete="off" />
    <div class="stat"><b id="n-people">0</b> people</div>
    <div class="stat"><b id="n-nodes">0</b> promoted nodes</div>
  </div>
  <div class="filters" id="filters"></div>

  <div class="bridge">
    <div class="b-ico">🌉</div>
    <div class="b-txt">${b.bridgeBanner}</div>
  </div>

  <section id="s-bridge"><h2>${b.bridgeHeading}</h2><div class="grid" id="g-bridge"></div></section>
  <section id="s-people"><h2>${b.membersHeading}</h2><div class="grid" id="g-people"></div></section>
  <div class="empty" id="empty" style="display:none">No one matches that search.</div>
</div>

<footer>${footer}
</footer>

<script src="people.js"></script>
<script>
  const DATA = window.${cohort.globalVar} || {people:[]};
  const people = DATA.people || [];
  const initials = n => n.split(/\\s+/).map(w=>w[0]).slice(0,2).join("").toUpperCase();
  let activeTags = new Set();

  document.getElementById("updated").textContent = DATA.updated || "";
  const bridges = people.filter(p=>p.kind==="bridge");
  document.getElementById("bridge-names").textContent =
    bridges.map(b=>b.name.split(" ")[0]).join(" & ") || "its bridge people";

  // tag universe
  const allTags = [...new Set(people.flatMap(p=>p.tags||[]))].sort();
  const fEl = document.getElementById("filters");
  allTags.forEach(t=>{
    const el=document.createElement("span"); el.className="tag"; el.textContent=t;
    el.onclick=()=>{ el.classList.toggle("on");
      el.classList.contains("on")?activeTags.add(t):activeTags.delete(t); render(); };
    fEl.appendChild(el);
  });

  function card(p){
    const memberBadge = ${badgeField}
      ? \`<span class="badge node" title="\${${badgeField}}">node</span>\`
      : \`<span class="badge">roster</span>\`;
    const av = p.avatar ? \`<img src="\${p.avatar}" alt="">\` : initials(p.name);
    const links = [];
    if(p.githubUrl) links.push(\`<a href="\${p.githubUrl}" target="_blank">@\${p.github}</a>\`);
    if(p.channels?.signal) links.push(\`<span class="loc">Signal \${p.channels.signal}</span>\`);
    if(p.channels?.telegram) links.push(\`<span class="loc">TG \${p.channels.telegram}</span>\`);
    const chips = (p.tags||[]).map(t=>\`<span class="c">\${t}</span>\`).join("");
    return \`<div class="card \${p.kind==='bridge'?'bridge-card':''}">
      \${memberBadge}
      <div class="top">
        <div class="av">\${av}</div>
        <div><div class="nm">\${p.name}</div><div class="rl">\${p.role||""}</div>
        <div class="loc">\${p.location||""}</div></div>
      </div>
      \${p.note?\`<div class="note">\${p.note}</div>\`:""}
      <div class="chips">\${chips}</div>
      <div class="links">\${links.join("")}</div>
    </div>\`;
  }

  function match(p,q){
    if(activeTags.size && !(p.tags||[]).some(t=>activeTags.has(t))) return false;
    if(!q) return true;
    const hay=[p.name,p.role,p.location,p.github,p.note,...(p.tags||[])].join(" ").toLowerCase();
    return hay.includes(q);
  }

  function render(){
    const q=document.getElementById("q").value.trim().toLowerCase();
    const br=bridges.filter(p=>match(p,q));
    const mem=people.filter(p=>p.kind!=="bridge").filter(p=>match(p,q));
    document.getElementById("g-bridge").innerHTML=br.map(card).join("");
    document.getElementById("g-people").innerHTML=mem.map(card).join("");
    document.getElementById("s-bridge").style.display=br.length?"":"none";
    document.getElementById("s-people").style.display=mem.length?"":"none";
    document.getElementById("empty").style.display=(br.length+mem.length)?"none":"";
    document.getElementById("n-people").textContent=people.length;
    document.getElementById("n-nodes").textContent=people.filter(p=>p.memoryNode).length;
  }
  document.getElementById("q").addEventListener("input",render);
  render();
</script>
</body>
</html>
`;
}
